(defun u8 (n)
  (logand n #xff))

(defun u16 (n)
  (vector (u8 n)
          (u8 (ash n -8))))

(defun u32 (n)
  (vector (u8 n)
          (u8 (ash n -8))
          (u8 (ash n -16))
          (u8 (ash n -24))))

(defun u64 (n)
  (vector (u8 n)
          (u8 (ash n -8))
          (u8 (ash n -16))
          (u8 (ash n -24))
          (u8 (ash n -32))
          (u8 (ash n -40))
          (u8 (ash n -48))
          (u8 (ash n -56))))

(defun bytes (&rest parts)
  (apply #'concatenate 'vector parts))

(defun pad (data size)
  (let ((out (make-array size
                         :element-type '(unsigned-byte 8)
                         :initial-element 0)))
    (replace out data)
    out))

(defun ascii (string)
  (map 'vector #'char-code string))

(defun utf16 (string)
  (let ((out (make-array (* 2 (1+ (length string)))
                         :element-type '(unsigned-byte 8)
                         :initial-element 0)))
    (loop for i from 0 below (length string)
          for c across string
          for n = (char-code c)
          do
            (setf (aref out (* i 2)) (u8 n))
            (setf (aref out (1+ (* i 2))) (u8 (ash n -8))))
    out))

(defun file-read (path)
  (with-open-file (s path :element-type '(unsigned-byte 8))
    (let ((data (make-array (file-length s))))
      (read-sequence data s)
      data)))

(defun string-between (source start)
  (let ((a (search start source)))
    (unless a
      (error "wtf: invalid program"))
    (let* ((begin (+ a (length start)))
           (end (position #\" source :start begin)))
      (unless end
        (error "wtf: unterminated string"))
      (subseq source begin end))))

(defun source-string (path)
  (with-open-file (s path)
    (let ((source (make-string (file-length s))))
      (read-sequence source s)
      source)))

(defun parse (source)
  (let ((text (string-trim '(#\Space #\Tab #\Newline #\Return)
                           source)))
    (unless (and (>= (length text) 9)
                 (string= "(print \"" text :end2 8)
                 (char= (char text (1- (length text))) #\)))
      (error "wtf: expected (print \"string\")"))
    (let ((body (subseq text 8 (1- (length text)))))
      (unless (char= (char body (1- (length body))) #\")
        (error "wtf: expected string"))
      (subseq body 0 (1- (length body))))))

(defun code (message)
  (let* ((data (utf16 message))
         (code-size 20)
         (message-rva #x2000)
         (next-rip (+ #x1000 14))
         (disp (- message-rva next-rip)))
    (bytes
     #(#x48 #x8b #x42 #x38)
     #(#x48 #x89 #xc1)
     #(#x48 #x8d #x15)
     (u32 disp)
     #(#xff #x50 #x08)
     #(#x31 #xc0)
     #(#xc3))))

(defun dos-header ()
  (let ((out (make-array #x80
                         :element-type '(unsigned-byte 8)
                         :initial-element 0)))
    (setf (aref out #x00) #x4d)
    (setf (aref out #x01) #x5a)
    (replace out (u32 #x80) :start1 #x3c)
    out))

(defun optional-header ()
  (bytes
   (u16 #x20b)
   #(#x00 #x00)
   (u32 #x200)
   (u32 #x400)
   (u32 #x000)
   (u32 #x1000)
   (u32 #x1000)
   (u64 #x0000000000000000)
   (u32 #x1000)
   (u32 #x200)
   (u16 1)
   (u16 1)
   (u16 0)
   (u16 0)
   (u16 1)
   (u16 0)
   (u32 0)
   (u32 #x3000)
   (u32 #x200)
   (u32 0)
   (u16 10)
   (u16 0)
   (u64 #x100000)
   (u64 #x1000)
   (u64 #x100000)
   (u64 #x1000)
   (u32 0)
   (u32 16)
   (make-array 128
               :element-type '(unsigned-byte 8)
               :initial-element 0)))

(defun section-header (name virtual-size virtual-address raw-size raw-address characteristics)
  (let ((out (make-array 40
                         :element-type '(unsigned-byte 8)
                         :initial-element 0)))
    (replace out (ascii name))
    (replace out (u32 virtual-size) :start1 8)
    (replace out (u32 virtual-address) :start1 12)
    (replace out (u32 raw-size) :start1 16)
    (replace out (u32 raw-address) :start1 20)
    (replace out (u32 0) :start1 24)
    (replace out (u32 0) :start1 28)
    (replace out (u16 0) :start1 32)
    (replace out (u16 0) :start1 34)
    (replace out (u32 characteristics) :start1 36)
    out))

(defun pe-header ()
  (bytes
   (ascii "PE")
   #(#x00 #x00)
   (u16 #x8664)
   (u16 2)
   (u32 0)
   (u32 0)
   (u32 0)
   (u16 #xf0)
   (u16 #x0022)
   (optional-header)
   (section-header ".text" 20 #x1000 #x200 #x200 #x60000020)
   (section-header ".rdata" 256 #x2000 #x200 #x400 #x40000040)))

(defun image (message)
  (let* ((header (bytes (dos-header)
                        (make-array 0
                                    :element-type '(unsigned-byte 8))
                        (pe-header)))
         (headers (pad header #x200))
         (text (pad (code message) #x200))
         (data (pad (utf16 message) #x200)))
    (bytes headers text data)))

(defun write-image (path data)
  (with-open-file (s path
                    :direction :output
                    :if-exists :supersede
                    :element-type '(unsigned-byte 8))
    (write-sequence data s)))

(defun main ()
  (let ((args sb-ext:*posix-argv*))
    (unless (= (length args) 3)
      (format *error-output*
              "usage: wtf <input.lisp> <output.efi>~%")
      (sb-ext:exit :code 1))
    (let* ((input (second args))
           (output (third args))
           (source (source-string input))
           (message (parse source))
           (image (image message)))
      (write-image output image)
      (format t "wtf: ~a -> ~a~%" input output))))

(main)
